"""
ZigBlade Pentest Report Generator
Produces professional markdown security assessment reports.
"""
from datetime import datetime
from typing import Optional


class ReportGenerator:
    """Generate security assessment reports from ZigBlade findings."""

    def generate(
        self,
        networks: list,
        packets: list,
        keys: list,
        findings: list,
        log: list,
        session_start: datetime,
    ) -> str:
        duration = datetime.now() - session_start
        critical = [f for f in findings if f["severity"] == "CRITICAL"]
        high = [f for f in findings if f["severity"] == "HIGH"]
        medium = [f for f in findings if f["severity"] == "MEDIUM"]
        low = [f for f in findings if f["severity"] == "LOW"]

        report = f"""# ZigBlade IoT Security Assessment Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Duration:** {str(duration).split('.')[0]}
**Tool:** ZigBlade v0.1 (github.com/Miles0sage/zigblade)

---

## Executive Summary

| Metric | Value |
|--------|-------|
| Networks Discovered | {len(networks)} |
| Packets Captured | {len(packets)} |
| Keys Extracted | {len(keys)} |
| **Critical Findings** | **{len(critical)}** |
| **High Findings** | **{len(high)}** |
| Medium Findings | {len(medium)} |
| Low Findings | {len(low)} |

### Risk Rating: {"CRITICAL" if critical else "HIGH" if high else "MEDIUM" if medium else "LOW" if low else "PASS"}

---

## Discovered Networks

| PAN ID | Channel | Coordinator | RSSI | Security | Assessment |
|--------|---------|-------------|------|----------|------------|
"""
        for net in networks:
            report += (
                f"| 0x{net.pan_id:04X} | {net.channel} | {net.coordinator} "
                f"| {net.rssi} dBm | {'Yes' if net.security else 'No'} "
                f"| {net.security_assessment} |\n"
            )

        if keys:
            report += "\n## Extracted Keys\n\n"
            report += "| PAN ID | Channel | Method | Key |\n"
            report += "|--------|---------|--------|-----|\n"
            for key in keys:
                masked = key.network_key[:8] + "..." + key.network_key[-4:]
                report += f"| 0x{key.pan_id:04X} | {key.channel} | {key.method} | `{masked}` |\n"

        report += "\n## Findings\n\n"
        for i, finding in enumerate(sorted(findings, key=lambda f: {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}.get(f["severity"], 5)), 1):
            icon = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵", "INFO": "⚪"}.get(finding["severity"], "⚪")
            report += f"### {icon} Finding {i}: {finding['title']}\n\n"
            report += f"**Severity:** {finding['severity']}\n\n"
            report += f"{finding['description']}\n\n"
            if finding.get("evidence"):
                report += f"**Evidence:** `{finding['evidence']}`\n\n"
            report += "---\n\n"

        report += """## Recommendations

1. **Enable network-level security** on all Zigbee networks
2. **Use unique install codes** instead of the default trust center link key
3. **Enable frame counter validation** on all devices to prevent replay attacks
4. **Disable Touchlink commissioning** on production devices
5. **Implement application-layer encryption** for sensitive commands (lock/unlock)
6. **Monitor for rogue coordinators** using network intrusion detection
7. **Update firmware** on all IoT devices to latest versions
8. **Segment IoT networks** from corporate/home networks

---

## Methodology

This assessment used ZigBlade, an open-source IoT security testing platform,
to perform passive and active security analysis of IEEE 802.15.4 / Zigbee networks.

**Phases:**
1. Discovery — Passive beacon scanning across all 16 Zigbee channels
2. Analysis — Packet capture and decryption with known/extracted keys
3. Testing — Active security tests (replay, injection, fuzzing) where authorized
4. Reporting — Automated finding generation and severity classification

---

*Report generated by ZigBlade AI Agent*
*github.com/Miles0sage/zigblade*
"""
        return report
